// Code generated by Rig. DO NOT EDIT.
package mocks

import (
	"context"

	"github.com/edgar-sucre-uvi/rig/internal/domain"
)

type GetUserResult struct {
	Out0 *domain.User
	Out1 error
}

type UserRepositoryMock struct {
	GetUserChan chan GetUserResult
}

type UserRepositoryOption func(*UserRepositoryMock)

func NewUserRepositoryMock(opts ...UserRepositoryOption) *UserRepositoryMock {
	m := &UserRepositoryMock{
		GetUserChan: make(chan GetUserResult, 100),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

func WithGetUserResults(results ...GetUserResult) UserRepositoryOption {
	return func(m *UserRepositoryMock) {
		for _, res := range results {
			m.GetUserChan <- res
		}
	}
}

func (m *UserRepositoryMock) GetUser(ctx context.Context, id int) (*domain.User, error) {
	res := <-m.GetUserChan
	return res.Out0, res.Out1
}
