package main

import (
	"text/template"
)

var templateFuncs = template.FuncMap{
	"sub": func(a, b int) int { return a - b },
}

var mockTemplate = template.Must(
	template.New("rig-mock").
		Funcs(templateFuncs).
		Parse(`// Code generated by Rig. DO NOT EDIT.
package {{ .Package }}

{{ range .InterfaceDef.Methods }}
type {{ .Name }}Result struct {
	{{- range $i, $res := .Results }}
	Out{{ $i }} {{ $res.Type }}
	{{- end }}
}
{{ end }}

type {{ $.InterfaceDef.Name }}Mock struct {
	{{- range .InterfaceDef.Methods }}
	{{ .Name }}Chan chan {{ .Name }}Result
	{{- end }}
}

type {{ $.InterfaceDef.Name }}Option func(*{{ $.InterfaceDef.Name }}Mock)

func New{{ $.InterfaceDef.Name }}Mock(opts ...{{ $.InterfaceDef.Name }}Option) *{{ $.InterfaceDef.Name }}Mock {
	m := &{{ $.InterfaceDef.Name }}Mock{
		{{- range .InterfaceDef.Methods }}
		{{ .Name }}Chan: make(chan {{ .Name }}Result, 100),
		{{- end }}
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

{{ range .InterfaceDef.Methods }}
func With{{ .Name }}Results(results ...{{ .Name }}Result) {{ $.InterfaceDef.Name }}Option {
	return func(m *{{ $.InterfaceDef.Name }}Mock) {
		for _, res := range results {
			m.{{ .Name }}Chan <- res
		}
	}
}
{{ end }}

{{ range .InterfaceDef.Methods }}
func (m *{{ $.InterfaceDef.Name }}Mock) {{ .Name }}(
	{{- range $i, $param := .Params -}}
	{{ if $param.Name }}{{ $param.Name }}{{ else }}arg{{ $i }}{{ end }} {{ $param.Type }}, 
	{{- end -}}
) (
	{{- range $i, $res := .Results -}}
	{{ $res.Type }}, 
	{{- end -}}
) {
	res := <-m.{{ .Name }}Chan
	{{ $results := .Results -}}
	return {{ range $i, $res := $results -}}
		res.Out{{ $i }}{{ if lt $i (sub (len $results) 1) }}, {{ end }}
	{{- end }}
}
{{ end }}
`))
