package main

import (
	"text/template"
)

var templateFuncs = template.FuncMap{
	"sub": func(a, b int) int { return a - b },
}

var mockTemplate = template.Must(
	template.New("rig-mock").
		Funcs(templateFuncs).
		Parse(`// Code generated by Rig. DO NOT EDIT.
package {{ .Package }}

import (
	"context"
)

{{ range .InterfaceDef.Methods }}
// {{ .Name }}Result stores the return values for the {{ .Name }} method.
type {{ .Name }}Result struct {
	{{- range $i, $res := .Results }}
	Out{{ $i }} {{ $res.Type }}
	{{- end }}
}
{{ end }}

// {{ .Name }}Mock is a channel-based concurrent mock for the {{ .Name }} interface.
type {{ .Name }}Mock struct {
	{{- range .Methods }}
	{{ .Name }}Chan chan {{ .Name }}Result
	{{- end }}
}

// {{ .Name }}Option defines a functional option for configuring the mock.
type {{ .Name }}Option func(*{{ .Name }}Mock)

// New{{ .Name }}Mock builds a configured mock using industrial functional options.
func New{{ .Name }}Mock(opts ...{{ .Name }}Option) *{{ .Name }}Mock {
	m := &{{ .Name }}Mock{
		{{- range .Methods }}
		{{ .Name }}Chan: make(chan {{ .Name }}Result, 100), // Buffered safely by default
		{{- end }}
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

{{ range .InterfaceDef.Methods }}
// With{{ .Name }}Results pre-loads the mock with a sequence of results for {{ .Name }}.
func With{{ .Name }}Results(results ...{{ .Name }}Result) {{ $.InterfaceDef.Name }}Option {
	return func(m *{{ $.InterfaceDef.Name }}Mock) {
		for _, res := range results {
			m.{{ .Name }}Chan <- res
		}
	}
}
{{ end }}

{{ range .InterfaceDef.Methods }}
// {{ .Name }} implements the {{ $.InterfaceDef.Name }} interface. It blocks until a result is queued.
func (m *{{ $.InterfaceDef.Name }}Mock) {{ .Name }}(
	{{- range $i, $param := .Params -}}
	{{ if $param.Name }}{{ $param.Name }}{{ else }}arg{{ $i }}{{ end }} {{ $param.Type }}, 
	{{- end -}}
) (
	{{- range $i, $res := .Results -}}
	{{ $res.Type }}, 
	{{- end -}}
) {
	res := <-m.{{ .Name }}Chan
	{{ $results := .Results -}}
	return {{ range $i, $res := $results -}}
		res.Out{{ $i }}{{ if lt $i (sub (len $results) 1) }}, {{ end }}
	{{- end }}
}
{{ end }}
`))
